CREATE PROCEDURE SPR_EXIST_COLUMN (@TABLE_NAME SYSNAME,@COLUMN_NAME SYSNAME)
AS 

SET NOCOUNT ON

DECLARE		@SQL	NVARCHAR(MAX);

SET @SQL = 'SELECT COUNT(1)	AS [RESULT]
			FROM	SYS.COLUMNS 
			WHERE	OBJECT_ID = OBJECT_ID(''' + QUOTENAME(@TABLE_NAME) + ''')
				AND	[NAME] = ''' + @COLUMN_NAME + ''''

EXEC SP_EXECUTESQL @SQL;

SET NOCOUNT OFF;

